name: Feature Request
description: Suggest a new feature for MathViz
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of MathViz would this feature affect?
      options:
        - Language Syntax
        - Compiler
        - Standard Library
        - Editor
        - CLI
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why do you need it?
      placeholder: |
        I'm trying to do X, but currently I have to Y, which is frustrating because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: syntax
    attributes:
      label: Proposed Syntax (if applicable)
      description: If this involves new language syntax, show an example.
      render: mviz
      placeholder: |
        // Example of how the new syntax would look
        fn example() {
            // ...
        }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: |
        I've also thought about...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples.
      placeholder: Add any other context here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the documentation to confirm this feature doesn't exist
          required: true
