# Generated by MathViz Compiler
# https://github.com/CyberSnakeH/MathViz

import numpy as np

from numba import jit, njit, vectorize, prange
import numba

from manim import *

from manim import Circle, Square, Create, FadeOut, Transform, BLUE, RED, GREEN
class CircleAnimation(Scene):
    def construct(self):
        circle = Circle()
        circle.set_fill(BLUE, 0.5)
        circle.set_stroke(BLUE, 2)
        square = Square()
        square.set_fill(RED, 0.5)
        self.play(Create(circle))
        self.wait(1)
        self.play(Transform(circle, square))
        self.wait(1)
        self.play(FadeOut(circle))
