"""
Unit tests for the MathViz Code Generator.
"""


class TestCodeGenBasics:
    """Basic code generation tests."""

    def test_empty_program(self, compile_source):
        """Empty program should produce header comments."""
        code = compile_source("")
        assert "# Generated by MathViz Compiler" in code

    def test_let_statement(self, compile_source):
        """Test let statement compilation."""
        code = compile_source("let x = 42")
        assert "x = 42" in code

    def test_let_with_type(self, compile_source):
        """Test let statement with type annotation."""
        code = compile_source("let x: Int = 42")
        assert "x: int = 42" in code

    def test_let_generic_type(self, compile_source):
        """Test let with generic type."""
        code = compile_source("let items: List[Int] = [1, 2]")
        assert "items: list[int]" in code


class TestCodeGenFunctions:
    """Tests for function code generation."""

    def test_simple_function(self, compile_source):
        """Test simple function generation."""
        code = compile_source("""
fn add(x: Int, y: Int) -> Int {
    return x + y
}
""")
        assert "def add(x: int, y: int) -> int:" in code
        assert "return (x + y)" in code

    def test_function_with_defaults(self, compile_source):
        """Test function with default parameters."""
        code = compile_source('fn greet(name: String = "World") { return name }')
        assert "def greet(name: str = 'World'):" in code


class TestCodeGenClasses:
    """Tests for class code generation."""

    def test_simple_class(self, compile_source):
        """Test simple class generation."""
        code = compile_source("class Point { let x: Float }")
        assert "class Point:" in code
        assert "x: float" in code

    def test_class_with_base(self, compile_source):
        """Test class with inheritance."""
        code = compile_source("class Circle(Shape) { pass }")
        assert "class Circle(Shape):" in code


class TestCodeGenScenes:
    """Tests for Manim scene code generation."""

    def test_scene_generation(self, compile_source):
        """Test scene generates Scene subclass."""
        code = compile_source("scene MyAnimation { pass }")
        assert "class MyAnimation(Scene):" in code


class TestCodeGenControlFlow:
    """Tests for control flow code generation."""

    def test_if_statement(self, compile_source):
        """Test if statement generation."""
        code = compile_source("if x > 0 { let y = 1 }")
        assert "if (x > 0):" in code
        assert "y = 1" in code

    def test_if_else(self, compile_source):
        """Test if-else generation."""
        code = compile_source("if x > 0 { let y = 1 } else { let y = 2 }")
        assert "if (x > 0):" in code
        assert "else:" in code

    def test_if_elif_else(self, compile_source):
        """Test if-elif-else chain."""
        code = compile_source("""
if x > 0 {
    let result = 1
} elif x < 0 {
    let result = -1
} else {
    let result = 0
}
""")
        assert "if (x > 0):" in code
        assert "elif (x < 0):" in code
        assert "else:" in code

    def test_for_loop(self, compile_source):
        """Test for loop generation."""
        code = compile_source("for i in items { print(i) }")
        assert "for i in items:" in code

    def test_while_loop(self, compile_source):
        """Test while loop generation."""
        code = compile_source("while x > 0 { x = x - 1 }")
        assert "while (x > 0):" in code


class TestCodeGenExpressions:
    """Tests for expression code generation."""

    def test_arithmetic(self, compile_source):
        """Test arithmetic expression generation."""
        code = compile_source("let x = 1 + 2 * 3")
        assert "x = (1 + (2 * 3))" in code

    def test_comparison(self, compile_source):
        """Test comparison expression generation."""
        code = compile_source("let x = a == b")
        assert "x = (a == b)" in code

    def test_logical(self, compile_source):
        """Test logical expression generation."""
        code = compile_source("let x = a and b")
        assert "x = (a and b)" in code

    def test_unary_minus(self, compile_source):
        """Test unary minus generation."""
        code = compile_source("let x = -5")
        assert "x = (-5)" in code

    def test_unary_not(self, compile_source):
        """Test unary not generation."""
        code = compile_source("let x = not true")
        assert "x = (not True)" in code

    def test_function_call(self, compile_source):
        """Test function call generation."""
        code = compile_source("foo(42)")
        assert "foo(42)" in code

    def test_method_call(self, compile_source):
        """Test method call generation."""
        code = compile_source("obj.method(1, 2)")
        assert "obj.method(1, 2)" in code

    def test_index_access(self, compile_source):
        """Test index access generation."""
        code = compile_source("let x = arr[0]")
        assert "x = arr[0]" in code

    def test_member_access(self, compile_source):
        """Test member access generation."""
        code = compile_source("let x = obj.field")
        assert "x = obj.field" in code


class TestCodeGenMathOperators:
    """Tests for mathematical operator code generation."""

    def test_element_of(self, compile_source):
        """Test element-of operator compilation."""
        code = compile_source("let x = 1 ∈ S")
        assert "is_element(1, S)" in code
        assert "from mathviz.runtime import" in code

    def test_not_element_of(self, compile_source):
        """Test not-element-of operator compilation."""
        code = compile_source("let x = 1 ∉ S")
        assert "is_not_element(1, S)" in code

    def test_subset(self, compile_source):
        """Test subset operator compilation."""
        code = compile_source("let x = A ⊆ B")
        assert "is_subset(A, B)" in code

    def test_superset(self, compile_source):
        """Test superset operator compilation."""
        code = compile_source("let x = A ⊇ B")
        assert "is_superset(A, B)" in code

    def test_union(self, compile_source):
        """Test union operator compilation."""
        code = compile_source("let x = A ∪ B")
        assert "set_union(A, B)" in code

    def test_intersection(self, compile_source):
        """Test intersection operator compilation."""
        code = compile_source("let x = A ∩ B")
        assert "set_intersection(A, B)" in code

    def test_set_difference(self, compile_source):
        """Test set difference operator compilation."""
        code = compile_source("let x = A ∖ B")
        assert "set_difference(A, B)" in code

    def test_power_operator(self, compile_source):
        """Test power operator uses Python **."""
        code = compile_source("let x = 2 ^ 10")
        assert "(2 ** 10)" in code


class TestCodeGenLiterals:
    """Tests for literal code generation."""

    def test_list_literal(self, compile_source):
        """Test list literal generation."""
        code = compile_source("let x = [1, 2, 3]")
        assert "x = [1, 2, 3]" in code

    def test_set_literal(self, compile_source):
        """Test set literal generation."""
        code = compile_source("let x = {1, 2, 3}")
        assert "x = {1, 2, 3}" in code

    def test_empty_set(self, compile_source):
        """Test empty set uses set() function."""
        code = compile_source("let x = ∅")
        assert "x = set()" in code

    def test_dict_literal(self, compile_source):
        """Test dictionary literal generation."""
        code = compile_source('let x = {"a": 1, "b": 2}')
        assert "'a': 1" in code
        assert "'b': 2" in code

    def test_string_literal(self, compile_source):
        """Test string literal generation."""
        code = compile_source('let x = "hello"')
        assert "x = 'hello'" in code

    def test_boolean_literals(self, compile_source):
        """Test boolean literal generation."""
        code = compile_source("let x = true")
        assert "x = True" in code
        code = compile_source("let x = false")
        assert "x = False" in code


class TestCodeGenImports:
    """Tests for import code generation."""

    def test_simple_import(self, compile_source):
        """Test simple import generation."""
        code = compile_source("import manim")
        assert "import manim" in code

    def test_import_as(self, compile_source):
        """Test import with alias."""
        code = compile_source("import numpy as np")
        assert "import numpy as np" in code

    def test_from_import(self, compile_source):
        """Test from...import generation."""
        code = compile_source("from manim import Circle, Square")
        assert "from manim import Circle, Square" in code


class TestCodeGenIntegration:
    """Integration tests for code generation."""

    def test_complete_program(self, compile_source):
        """Test a complete MathViz program."""
        source = """
import manim

scene CircleAnimation {
    fn construct() {
        let circle = Circle()
        let square = Square()
    }
}

fn calculate(x: Int, y: Int) -> Int {
    if x > y {
        return x - y
    } else {
        return y - x
    }
}
"""
        code = compile_source(source)
        assert "import manim" in code
        assert "class CircleAnimation(Scene):" in code
        assert "def construct():" in code
        assert "def calculate(x: int, y: int) -> int:" in code

    def test_math_operations_program(self, compile_source):
        """Test program with mathematical operations."""
        source = """
let A = {1, 2, 3}
let B = {2, 3, 4}

let union_result = A ∪ B
let intersection_result = A ∩ B
let is_member = 1 ∈ A
let is_subset = A ⊆ B
"""
        code = compile_source(source)
        assert "set_union(A, B)" in code
        assert "set_intersection(A, B)" in code
        assert "is_element(1, A)" in code
        assert "is_subset(A, B)" in code


class TestCodeGenAnimate:
    """Tests for animate property code generation."""

    def test_animate_property(self, compile_source):
        """Test animate property generates correct Python."""
        code = compile_source("circle.animate.scale(2)")
        assert "circle.animate.scale(2)" in code

    def test_animate_chained(self, compile_source):
        """Test chained animate methods."""
        code = compile_source("circle.animate.scale(2).shift(RIGHT)")
        assert "circle.animate.scale(2).shift(RIGHT)" in code

    def test_animate_in_scene(self, compile_source):
        """Test animate in scene context."""
        source = """
scene TestScene {
    fn construct(self) {
        let c = Circle()
        play(c.animate.scale(2))
    }
}
"""
        code = compile_source(source)
        assert "c.animate.scale(2)" in code

    def test_animate_with_set_color(self, compile_source):
        """Test animate with set_color method."""
        code = compile_source("text.animate.set_color(RED)")
        assert "text.animate.set_color(RED)" in code
